language: node_js
node_js:
  - "8"
# Cache node_modules
cache:
  directories:   
    - "node_modules"
install:
  - npm install

script:
  # update Protractor and Selenium including ChromeDriver
  - npm run update-server
  # launch Selenium standalone in the background
  - npm run start-server
  # run Protractor E2E tests
  - npm run ci
