name: CI
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: npm i
      - name: run test
        run: npm run trial
